name: SlowVote

main: com.swifteh.SlowVote

version: 1.4
authors: [swifteh, SergeantMajorME]
description: voting thing
depends: [Votifier]
commands:
    svreset:
        description: resets a players creeperspeed
    svsetspawn:
    mend:
        description: repairs the item in your hand
    svtestcommand:
permissions:
    sv.mod:
        default: op
    sv.bypass:
        default: op
    sv.admin:
        default: op
    sv.demote:
        default: false