name: SlowVote

main: com.swifteh.SlowVote

version: 1.0
authors: [swifteh, SergeantMajorME]

description: voting thing

depends: [Votifier]
commands:

    svreset:
        description: resets a players creeperspeed

    svsetspawn:
permissions:
    sv.mod:
        default: op

    sv.bypass:

        default: op

    sv.admin:

        default: op